// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// O bare "dotenv/config" só carrega .env — este projeto guarda os secrets em
// .env.local (não existe .env). Carrega os dois, .env.local por cima, mesmo
// padrão do prisma/seed.ts.
config({ path: ".env" });
config({ path: ".env.local", override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // CLI (migrate/introspect/studio) precisa de conexão de sessão, não do
    // pooler em modo transação — por isso usa DIRECT_URL aqui, não DATABASE_URL.
    // Em modo transação (pooler:6543) o Migrate trava tentando criar/derrubar
    // o shadow database, porque o pooler não sustenta operações de sessão.
    // O PrismaClient em runtime usa DATABASE_URL (pooler) via driver adapter,
    // configurado direto no código da aplicação, não por este arquivo.
    url: process.env["DIRECT_URL"],
  },
});
